### PR TITLE
fix mismatch in http contact types (not reading format field and norm…

### PR DESCRIPTION
**Pull request by rileyberton**
…alize url field)

### CODE REVIEW

**Review by dhaifley — CHANGES_REQUESTED** [review]
This looks good, but I would do two things. 1) Run make fmt from the root project directory to make sure your code is properly gofmt'ed. And, 2) I know the test code is commented out mostly for this resource type, but I would still update the test sample to reflect the change from address to url (in circonus/resource_circonus_contact_test.go).

**Comment by rileyberton** [comment]
requested changes applied

**Review by dhaifley — APPROVED** [review]
This looks good to me. Ok to merge.

**Comment by rileyberton** [comment]
I don't have merge permissions.. Can I get a merge and a release with the fix?

**Comment by rileyberton** [comment]
@dhaifley Thanks for the merge and release.  I see the release here of 0.12.4 but I don't see the release in the terraform.io registry.  it still lists 0.12.3.  Is there something that needs to happen to kick that to 0.12.4?

**Comment by rileyberton** [comment]
Looks like the builds are missing as artifacts in the 0.12.4 release like they are in prior releases.

**Comment by dhaifley** [comment]
Hi Riley. There is a process involved with terraform releases of which I was not aware. This has been completed now, so you should be able to see the new release on terraform.io.

**Comment by rileyberton** [comment]
working!  thanks!

**Pull request merged**
